name: Build and Test
on: [push]
jobs:
  Ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GetGo  
        uses: actions/setup-go@v2
        with:
            go-version: '1.9.3'


      - name: Build
        run: |
          cd oxfsgo
          go get github.com/io-core/oxfs-linux/oxfsgo
          go build cmd/oxfstool.go

      - name: Test
        run: |
          cd oxfsgo
          unzip RISCimg.zip
          ls -alh
          ./oxfstool -V

  MacOS-build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GetGo  
        uses: actions/setup-go@v2
        with:
            go-version: '1.9.3'

      - name: Build
        run: |
          cd oxfsgo
          go get github.com/io-core/oxfs-linux/oxfsgo
          go build cmd/oxfstool.go

      - name: Test
        run: |
          cd oxfsgo
          unzip RISCimg.zip
          ls -alh
          ./oxfstool -V


