name: Build and Test
on: [push]
jobs:
  Ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GetGo  
        uses: actions/setup-go@v2
        with:
            go-version: '1.9.3'

      - name: Install Dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          

      - name: Build
        run: |
          go version

      - name: Test
        run: |
          ls -alh

  MacOS-build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GetGo  
        uses: actions/setup-go@v2
        with:
            go-version: '1.9.3'

      - name: Install Dependencies
        run: | 
          echo "don't need nuthin'"

      - name: Build
        run: |
          go version

      - name: Test
        run: |
          ls -alh  

